### ISSUE TITLE
好奇现在聊天功能在哪

### ISSUE THREAD

**Issue by readlnh** [sirodeneko/giligili-go#1]
我看代码里有聊天功能,但是网站上没找到...

**Comment by sirodeneko** [comment]
emmmm因为还没写好咕了

**Comment by sirodeneko** [comment]
网站的源码其实是可以看到也有的，但是没被我显示出来

**Comment by sirodeneko** [comment]
https://github.com/sirodeneko/giligili-vue/blob/master/src/components/NavBar.vue
这里第7行被我注释掉了
